/*
MySQL Backup
Database: perpuskumpulkan
Backup Time: 2023-12-12 14:28:16
*/

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `perpuskumpulkan`.`akun`;
DROP TABLE IF EXISTS `perpuskumpulkan`.`anggota`;
DROP TABLE IF EXISTS `perpuskumpulkan`.`buku`;
DROP TABLE IF EXISTS `perpuskumpulkan`.`detail_peminjaman`;
DROP TABLE IF EXISTS `perpuskumpulkan`.`detail_pengembalian`;
DROP TABLE IF EXISTS `perpuskumpulkan`.`entry`;
DROP TABLE IF EXISTS `perpuskumpulkan`.`inventaris`;
DROP TABLE IF EXISTS `perpuskumpulkan`.`kategori`;
DROP TABLE IF EXISTS `perpuskumpulkan`.`peminjaman`;
DROP TABLE IF EXISTS `perpuskumpulkan`.`penerbit`;
DROP TABLE IF EXISTS `perpuskumpulkan`.`pengembalian`;
DROP TABLE IF EXISTS `perpuskumpulkan`.`penjaga`;
CREATE TABLE `akun` (
  `USERNAME` varchar(50) NOT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `PASSWORD` varchar(50) DEFAULT NULL,
  `LEVEL` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`USERNAME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `anggota` (
  `NISN` varchar(20) NOT NULL,
  `NAMA_ANGGOTA` varchar(50) DEFAULT NULL,
  `EMAIL_ANGGOTA` varchar(50) DEFAULT NULL,
  `TELEPON_ANGGOTA` varchar(15) DEFAULT NULL,
  `JENIS_KELAMIN_ANGGOTA` varchar(15) DEFAULT NULL,
  `TANGGAL_BERGABUNG_ANGGOTA` date DEFAULT NULL,
  `GAMBAR` longblob DEFAULT NULL,
  PRIMARY KEY (`NISN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `buku` (
  `ISBN` varchar(255) NOT NULL,
  `ID_PENERBIT` varchar(255) DEFAULT NULL,
  `ID_KATEGORI` varchar(255) DEFAULT NULL,
  `JUDUL_BUKU` varchar(255) DEFAULT NULL,
  `PENGARANG_BUKU` varchar(255) DEFAULT NULL,
  `TAHUN_TERBIT` varchar(4) DEFAULT NULL,
  `DESKRIPSI` varchar(255) DEFAULT NULL,
  `CATATAN_UMUM` varchar(255) DEFAULT NULL,
  `JENIS_BUKU` varchar(25) DEFAULT NULL,
  `GAMBAR` longblob DEFAULT NULL,
  PRIMARY KEY (`ISBN`),
  KEY `FK_BUKU_RELATIONS_KATEGORI` (`ID_KATEGORI`),
  KEY `FK_BUKU_RELATIONS_PENERBIT` (`ID_PENERBIT`),
  CONSTRAINT `FK_BUKU_RELATIONS_KATEGORI` FOREIGN KEY (`ID_KATEGORI`) REFERENCES `kategori` (`ID_KATEGORI`),
  CONSTRAINT `FK_BUKU_RELATIONS_PENERBIT` FOREIGN KEY (`ID_PENERBIT`) REFERENCES `penerbit` (`ID_PENERBIT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `detail_peminjaman` (
  `ID_DETAIL_PEMINJAMAN` varchar(50) NOT NULL,
  `ID_BUKU` varchar(20) DEFAULT NULL,
  `ID_PEMINJAMAN` varchar(20) DEFAULT NULL,
  `STATUS_PENGEMBALIAN` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID_DETAIL_PEMINJAMAN`),
  KEY `FK_DETAIL_P_RELATIONS_ENTRI_BU` (`ID_BUKU`),
  KEY `FK_DETAIL_P_RELATIONS_PEMINJAM` (`ID_PEMINJAMAN`),
  CONSTRAINT `FK_DETAIL_P_RELATIONS_ENTRI_BU` FOREIGN KEY (`ID_BUKU`) REFERENCES `entry` (`ID_BUKU`),
  CONSTRAINT `FK_DETAIL_P_RELATIONS_PEMINJAM` FOREIGN KEY (`ID_PEMINJAMAN`) REFERENCES `peminjaman` (`ID_PEMINJAMAN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `detail_pengembalian` (
  `ID_DETAIL_PENGEMBALIAN` varchar(50) NOT NULL,
  `ID_PENGEMBALIAN` varchar(25) DEFAULT NULL,
  `ID_BUKU` varchar(20) DEFAULT NULL,
  `SUBTOTAL_DENDA` float DEFAULT NULL,
  PRIMARY KEY (`ID_DETAIL_PENGEMBALIAN`),
  KEY `FK_DETAIL_P_REFERENCE_ENTRI_BU` (`ID_BUKU`),
  KEY `FK_DETAIL_P_RELATIONS_PENGEMBA` (`ID_PENGEMBALIAN`),
  CONSTRAINT `FK_DETAIL_P_REFERENCE_ENTRI_BU` FOREIGN KEY (`ID_BUKU`) REFERENCES `entry` (`ID_BUKU`),
  CONSTRAINT `FK_DETAIL_P_RELATIONS_PENGEMBA` FOREIGN KEY (`ID_PENGEMBALIAN`) REFERENCES `pengembalian` (`ID_PENGEMBALIAN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `entry` (
  `ID_BUKU` varchar(20) NOT NULL,
  `ISBN` varchar(100) DEFAULT NULL,
  `NO_INVENTARIS` varchar(50) DEFAULT NULL,
  `TANGGAL_ENTRI` date DEFAULT NULL,
  `WAKTU_ENTRI` time DEFAULT NULL,
  `BENTUK_FISIK` varchar(25) DEFAULT NULL,
  `STATUS_KETERSEDIAAN` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`ID_BUKU`),
  KEY `FK_ENTRI_BU_RELATIONS_INVENTAR` (`NO_INVENTARIS`),
  KEY `FK_ENTRI_BU_RELATIONS_BUKU` (`ISBN`),
  CONSTRAINT `FK_ENTRI_BU_RELATIONS_BUKU` FOREIGN KEY (`ISBN`) REFERENCES `buku` (`ISBN`),
  CONSTRAINT `FK_ENTRI_BU_RELATIONS_INVENTAR` FOREIGN KEY (`NO_INVENTARIS`) REFERENCES `inventaris` (`NO_INVENTARIS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `inventaris` (
  `NO_INVENTARIS` varchar(50) NOT NULL,
  `LOKASI` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`NO_INVENTARIS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `kategori` (
  `ID_KATEGORI` varchar(20) NOT NULL,
  `NAMA_KATEGORI` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_KATEGORI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `peminjaman` (
  `ID_PEMINJAMAN` varchar(20) NOT NULL,
  `ID_PENJAGA` varchar(25) DEFAULT NULL,
  `NISN` varchar(20) DEFAULT NULL,
  `TANGGAL_PEMINJAMAN` date DEFAULT NULL,
  `TANGGAL_PENGEMBALIAN` date DEFAULT NULL,
  `STATUS_PEMINJAMAN` varchar(25) DEFAULT NULL,
  `JUMLAH_PINJAMAN` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_PEMINJAMAN`),
  KEY `FK_PEMINJAM_RELATIONS_PENJAGA_` (`ID_PENJAGA`),
  KEY `FK_PEMINJAM_RELATIONS_ANGGOTA` (`NISN`),
  CONSTRAINT `FK_PEMINJAM_RELATIONS_ANGGOTA` FOREIGN KEY (`NISN`) REFERENCES `anggota` (`NISN`),
  CONSTRAINT `FK_PEMINJAM_RELATIONS_PENJAGA_` FOREIGN KEY (`ID_PENJAGA`) REFERENCES `penjaga` (`ID_PENJAGA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `penerbit` (
  `ID_PENERBIT` varchar(50) NOT NULL,
  `NAMA_PENERBIT` varchar(200) DEFAULT NULL,
  `KOTA_TERBIT` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_PENERBIT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `pengembalian` (
  `ID_PENGEMBALIAN` varchar(25) NOT NULL,
  `ID_PENJAGA` varchar(25) DEFAULT NULL,
  `NISN` varchar(20) DEFAULT NULL,
  `TANGGAL_DIKEMBALIKAN` date DEFAULT NULL,
  `TOTAL_DENDA` float DEFAULT NULL,
  `ID_PEMINJAMAN` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID_PENGEMBALIAN`),
  KEY `FK_PENGEMBA_RELATIONS_PENJAGA_` (`ID_PENJAGA`),
  KEY `FK_PENGEMBA_RELATIONS_ANGGOTA` (`NISN`),
  KEY `FK_PENGEMBALIAN_RELATIONS_PEMINJAMAN` (`ID_PEMINJAMAN`),
  CONSTRAINT `FK_PENGEMBALIAN_RELATIONS_PEMINJAMAN` FOREIGN KEY (`ID_PEMINJAMAN`) REFERENCES `peminjaman` (`ID_PEMINJAMAN`),
  CONSTRAINT `FK_PENGEMBA_RELATIONS_ANGGOTA` FOREIGN KEY (`NISN`) REFERENCES `anggota` (`NISN`),
  CONSTRAINT `FK_PENGEMBA_RELATIONS_PENJAGA_` FOREIGN KEY (`ID_PENJAGA`) REFERENCES `penjaga` (`ID_PENJAGA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `penjaga` (
  `ID_PENJAGA` varchar(25) NOT NULL,
  `NAMA_PENJAGA` varchar(100) DEFAULT NULL,
  `EMAIL_PENJAGA` varchar(100) DEFAULT NULL,
  `TELEPON_PENJAGA` varchar(20) DEFAULT NULL,
  `JENIS_KELAMIN_PENJAGA` varchar(20) DEFAULT NULL,
  `TANGGAL_BERGABUNG_PENJAGA` date DEFAULT NULL,
  `GAMBAR` longblob DEFAULT NULL,
  PRIMARY KEY (`ID_PENJAGA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
BEGIN;
LOCK TABLES `perpuskumpulkan`.`akun` WRITE;
DELETE FROM `perpuskumpulkan`.`akun`;
UNLOCK TABLES;
COMMIT;
BEGIN;
LOCK TABLES `perpuskumpulkan`.`anggota` WRITE;
DELETE FROM `perpuskumpulkan`.`anggota`;
UNLOCK TABLES;
COMMIT;
BEGIN;
LOCK TABLES `perpuskumpulkan`.`buku` WRITE;
DELETE FROM `perpuskumpulkan`.`buku`;
UNLOCK TABLES;
COMMIT;
BEGIN;
LOCK TABLES `perpuskumpulkan`.`detail_peminjaman` WRITE;
DELETE FROM `perpuskumpulkan`.`detail_peminjaman`;
UNLOCK TABLES;
COMMIT;
BEGIN;
LOCK TABLES `perpuskumpulkan`.`detail_pengembalian` WRITE;
DELETE FROM `perpuskumpulkan`.`detail_pengembalian`;
UNLOCK TABLES;
COMMIT;
BEGIN;
LOCK TABLES `perpuskumpulkan`.`entry` WRITE;
DELETE FROM `perpuskumpulkan`.`entry`;
UNLOCK TABLES;
COMMIT;
BEGIN;
LOCK TABLES `perpuskumpulkan`.`inventaris` WRITE;
DELETE FROM `perpuskumpulkan`.`inventaris`;
UNLOCK TABLES;
COMMIT;
BEGIN;
LOCK TABLES `perpuskumpulkan`.`kategori` WRITE;
DELETE FROM `perpuskumpulkan`.`kategori`;
UNLOCK TABLES;
COMMIT;
BEGIN;
LOCK TABLES `perpuskumpulkan`.`peminjaman` WRITE;
DELETE FROM `perpuskumpulkan`.`peminjaman`;
UNLOCK TABLES;
COMMIT;
BEGIN;
LOCK TABLES `perpuskumpulkan`.`penerbit` WRITE;
DELETE FROM `perpuskumpulkan`.`penerbit`;
UNLOCK TABLES;
COMMIT;
BEGIN;
LOCK TABLES `perpuskumpulkan`.`pengembalian` WRITE;
DELETE FROM `perpuskumpulkan`.`pengembalian`;
UNLOCK TABLES;
COMMIT;
BEGIN;
LOCK TABLES `perpuskumpulkan`.`penjaga` WRITE;
DELETE FROM `perpuskumpulkan`.`penjaga`;
UNLOCK TABLES;
COMMIT;
