/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import Config.Koneksi;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import java.awt.Insets;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.UIManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.security.NoSuchAlgorithmException;
import java.io.UnsupportedEncodingException;
import javax.swing.JPasswordField;
import main.MenuUtama;
/**
 *
 * @author Rifal
 */
//Muhammad Rifqi Naufal Irsyad (09010622010)
//MOCHAMMAD NASRUDDIN ZUHRI (09040622064)
//REYHAN DANY  (09040622076)
//RICO RAHMAT H(09020622041)
public class FormLogin extends javax.swing.JFrame {
    private Connection conn;
private String loggedInUsername;
    public FormLogin() {
        initComponents();
        
        this.conn = Koneksi.getConnection();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setBackground(new Color(0, 0, 0, 0));
        eye.setVisible(true);
        hideEye.setVisible(false);
        setActionButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustomTransparanGradien1 = new CustomSwing.PanelCustomTransparanGradien();
        eye = new javax.swing.JLabel();
        hideEye = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        btn_login = new rojerusan.RSMaterialButtonRectangle();
        jLabel4 = new javax.swing.JLabel();
        t_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCustomTransparanGradien1.setEndColor(new java.awt.Color(255, 255, 255));
        panelCustomTransparanGradien1.setOpacity(225);
        panelCustomTransparanGradien1.setRoundBottomLeft(20);
        panelCustomTransparanGradien1.setRoundBottomRight(20);
        panelCustomTransparanGradien1.setRoundTopLeft(20);
        panelCustomTransparanGradien1.setRoundTopRight(20);
        panelCustomTransparanGradien1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_eye_30px.png"))); // NOI18N
        panelCustomTransparanGradien1.add(eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 40, 40));

        hideEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_hide_30px.png"))); // NOI18N
        panelCustomTransparanGradien1.add(hideEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 40, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hai, Selamat Datang");
        panelCustomTransparanGradien1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 280, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Perpustakaan SMA Khadijah Surabaya");
        panelCustomTransparanGradien1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 340, -1));

        jLabel5.setText("Username");
        panelCustomTransparanGradien1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        panelCustomTransparanGradien1.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 320, 40));

        btn_login.setBackground(new java.awt.Color(123, 172, 110));
        btn_login.setText("Masuk");
        panelCustomTransparanGradien1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 240, 50));

        jLabel4.setText("Password");
        panelCustomTransparanGradien1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        panelCustomTransparanGradien1.add(t_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 320, 40));

        getContentPane().add(panelCustomTransparanGradien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 150, 410, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login Khadijah.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Menu");

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_exit_sign_20px_1.png"))); // NOI18N
        jMenu3.setText("Exit");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu3MouseClicked

    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
            UIManager.put("TextComponent.arc", 10);
        UIManager.put("Component.arc", 10);
            UIManager.put("ProgressBar.arc", 20);
            UIManager.put("Component.arrowType", "chevron");
            UIManager.put("Component.innerFocusWidth", 0);
            UIManager.put("Button.innerFocusWidth", 0);
            UIManager.put("ScrollBar.trackArc", 999);
            UIManager.put("ScrollBar.thumbArc", 999);
            UIManager.put("ScrollBar.trackInsets", new Insets(2, 4, 2, 4));
            UIManager.put("ScrollBar.thumbInsets", new Insets(2, 2, 2, 2));
            UIManager.put("ScrollBar.track", new Color(0xe0e0e0));

        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_login;
    private javax.swing.JLabel eye;
    private javax.swing.JLabel hideEye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private CustomSwing.PanelCustomTransparanGradien panelCustomTransparanGradien1;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables
public class GlobalVariables {
    public static String loggedInUsername;
  
}
    private void setActionButton() {
        hideEye.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                eye.setVisible(true);
                hideEye.setVisible(false);
                t_password.setEchoChar('*');
            }
        });
        eye.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                eye.setVisible(false);
                hideEye.setVisible(true);
                t_password.setEchoChar((char) 0);
            }
        });
        btn_login.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                prosesLogin();
            }
        });
        t_username.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                super.keyPressed(e);
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    btn_login.doClick();
                }
            }
        });
    }

    public String getMd5java(String message) {
        String digest = null;
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] hash = md.digest(message.getBytes("UTF-8"));
            StringBuilder sb = new StringBuilder(2 * hash.length);
            for (byte b : hash) {
                sb.append(String.format("%02x", b & 0xff));
            }
            digest = sb.toString();
        } catch (Exception e) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, e);
        }
        return digest;
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (t_username.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username harus diisi");
        } else if (t_password.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password harus diisi");
        } else {
            valid = true;
        }
        return valid;
    }

    private boolean checkLogin(String username, String password) {
        if (conn != null) {

            try {

                String sql = "SELECT * FROM akun WHERE username=? AND password=?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, username);
                st.setString(2, password);

                ResultSet rs = st.executeQuery();

                if (rs.next()) {
                    return true;
                }

            } catch (SQLException e) {
                e.printStackTrace();

            }

        }
        return false;
    }

  private void prosesLogin() {
    if (validasiInput()) {
        String username = t_username.getText();
        String password = new String(t_password.getPassword());
        String hashedPassword = getMd5java(password);

        if (checkLogin(username, hashedPassword)) {
           
            String userLevel = getUserLevel(username);

             GlobalVariables.loggedInUsername = username;
             
            if ("Admin".equals(userLevel)) {
                MenuUtama mn = new MenuUtama();
                mn.setVisible(true);
                mn.revalidate();
            } else if ("User".equals(userLevel)) {
                MenuSiswa ms = new MenuSiswa();
                ms.setVisible(true);
                ms.revalidate();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid user level",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }

            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Username and Password are not valid",
                    "Message", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}

private String getUserLevel(String username) {
    String level = "";
    if (conn != null) {
        try {
            String sql = "SELECT LEVEL FROM akun WHERE USERNAME=?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, username);

            ResultSet rs = st.executeQuery();

            if (rs.next()) {
                level = rs.getString("LEVEL");
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    return level;
}
public String getNamaPenjaga() {
        String namaPenjaga = "";
        if (conn != null) {
            try {
                String sql = "SELECT nama_penjaga FROM penjaga WHERE ID_PENJAGA=?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, loggedInUsername);

                ResultSet rs = st.executeQuery();

                if (rs.next()) {
                    namaPenjaga = rs.getString("nama_penjaga");
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return namaPenjaga;
    }
public String getNamaSantri() {
        String namaPenjaga = "";
        if (conn != null) {
            try {
                String sql = "SELECT nama_anggota FROM anggota WHERE NISN=?";
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1, loggedInUsername);

                ResultSet rs = st.executeQuery();

                if (rs.next()) {
                    namaPenjaga = rs.getString("nama_anggota");
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return namaPenjaga;
    }
 public void setLoggedInUsername(String username) {
        this.loggedInUsername = username;
    }

}
